Repository pauwels-labs/redact-store, pull requests merged in 2021-12, with the labels that each got.

#13 Upgrade Dependencies
  Cargo.lock
  Cargo.toml
  Dockerfile
  Dockerfile.dev
  src/bootstrap.rs
  src/main.rs
Labels: size/XL, approved

#14 fix: dockerfile was not caching correctly
  Dockerfile
  Dockerfile.dev
Labels: approved, size/S

#15 fix: Fix frequent connection errors when making multiple requests sim…
  src/bootstrap.rs
  src/main.rs
Labels: approved, size/XS

#16 fix: update rust in dockerfiles
  Dockerfile
  Dockerfile.dev
Labels: approved, size/S
